# Site Settings
title: "Tuan-Cuong Vuong — AI Research"
description: "AI Researcher | Research Assistant"
url: "https://cngvng.github.io"
baseurl: ""
locale: "en-US"

# Owner Information
owner_name: "Tuan-Cuong Vuong"
owner_affiliation: "Phenikaa University, Vietnam"
owner_email: "cngvng.work@gmail.com"

# Social Links
socials:
  scholar: "https://scholar.google.com/citations?user=GJuxF5QAAAAJ&hl=en"
  orcid: "https://orcid.org/0000-0002-0999-1950"
  github: "https://github.com/cngvng"
  linkedin: "https://www.linkedin.com/in/cng-vng"
  x: "https://x.com/cngvng413"
  university: "https://phenikaa-uni.edu.vn"

# Build Settings
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# Pagination (GitHub Pages compatible)
paginate: 8
paginate_path: "/page:num/"

# Collections
collections:
  publications:
    output: true
    permalink: /publications/:name/

# GitHub Pages safe mode
safe: true

# Highlighter compatible with GitHub Pages
highlighter: rouge

# Markdown processor
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# Defaults
defaults:
  - scope:
      path: ""
      type: "publications"
    values:
      layout: "publication"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Exclude
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .bundle
  - .sass-cache
  - _site
  - README.md
